version: '3.3'

services:
  redis:
    image: redis:latest
    volumes:
      - ./redis:/redis
    ports:
      - 6379:6379

  app:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: 'hypercorn'
    command: 'app:app -c config.toml'
    links:
      - redis
    env_file:
      - .env
    volumes:
      - ./:/usr/src/app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cttc-api.rule=Host(`cttc-api.9t9.tech`)"
      - "traefik.http.routers.cttc-api.tls=true"
      - "traefik.http.routers.cttc-api.tls.certresolver=lets-encrypt"
    networks:
      - internal
      - web

networks:
  web:
   external: true
  internal:
   external: false
