version: '3.3'

services:
  redis:
    image: redis:latest
    volumes:
      - ./redis:/redis
    ports:
      - 6379:6379

  app:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: 'hypercorn'
    command: 'app:app -c config.toml'
    links:
      - redis
    ports:
      - 8000:8000
    env_file:
      - .env
    volumes:
      - ./:/usr/src/app
